# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: git-secret
email: mail@sobolevn.me
description: > # this means to ignore newlines until "baseurl:"
  A bash-tool to store your private data inside a git repository.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sobolevn.github.io" # the base hostname & protocol for your site
github_username: sobolevn

# Seo settings:
gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
